//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.16 at 09:26:13 PM MSK 
//


package model.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for meal complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="meal">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="meal_id">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="user_id">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="meal_date">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}date">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="meal_kcal">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="meal_protein">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="meal_carbon">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="meal_fat">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "meal", propOrder = {
    "mealId",
    "userId",
    "mealDate",
    "mealKcal",
    "mealProtein",
    "mealCarbon",
    "mealFat"
})
public class Meal {

    public Meal() {
    }

    public Meal(int userId, XMLGregorianCalendar mealDate, int mealKcal, int mealProtein, int mealCarbon, int mealFat) {
        this.userId = userId;
        this.mealDate = mealDate;
        this.mealKcal = mealKcal;
        this.mealProtein = mealProtein;
        this.mealCarbon = mealCarbon;
        this.mealFat = mealFat;
    }

    public Meal(int mealId, int userId, XMLGregorianCalendar mealDate, int mealKcal, int mealProtein, int mealCarbon, int mealFat) {
        this.mealId = mealId;
        this.userId = userId;
        this.mealDate = mealDate;
        this.mealKcal = mealKcal;
        this.mealProtein = mealProtein;
        this.mealCarbon = mealCarbon;
        this.mealFat = mealFat;
    }

    @XmlElement(name = "meal_id")
    protected int mealId;
    @XmlElement(name = "user_id")
    protected int userId;
    @XmlElement(name = "meal_date", required = true)
    protected XMLGregorianCalendar mealDate;
    @XmlElement(name = "meal_kcal")
    protected int mealKcal;
    @XmlElement(name = "meal_protein")
    protected int mealProtein;
    @XmlElement(name = "meal_carbon")
    protected int mealCarbon;
    @XmlElement(name = "meal_fat")
    protected int mealFat;

    /**
     * Gets the value of the mealId property.
     * 
     */
    public int getMealId() {
        return mealId;
    }

    /**
     * Sets the value of the mealId property.
     * 
     */
    public void setMealId(int value) {
        this.mealId = value;
    }

    /**
     * Gets the value of the userId property.
     * 
     */
    public int getUserId() {
        return userId;
    }

    /**
     * Sets the value of the userId property.
     * 
     */
    public void setUserId(int value) {
        this.userId = value;
    }

    /**
     * Gets the value of the mealDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getMealDate() {
        return mealDate;
    }

    /**
     * Sets the value of the mealDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setMealDate(XMLGregorianCalendar value) {
        this.mealDate = value;
    }

    /**
     * Gets the value of the mealKcal property.
     * 
     */
    public int getMealKcal() {
        return mealKcal;
    }

    /**
     * Sets the value of the mealKcal property.
     * 
     */
    public void setMealKcal(int value) {
        this.mealKcal = value;
    }

    /**
     * Gets the value of the mealProtein property.
     * 
     */
    public int getMealProtein() {
        return mealProtein;
    }

    /**
     * Sets the value of the mealProtein property.
     * 
     */
    public void setMealProtein(int value) {
        this.mealProtein = value;
    }

    /**
     * Gets the value of the mealCarbon property.
     * 
     */
    public int getMealCarbon() {
        return mealCarbon;
    }

    /**
     * Sets the value of the mealCarbon property.
     * 
     */
    public void setMealCarbon(int value) {
        this.mealCarbon = value;
    }

    /**
     * Gets the value of the mealFat property.
     * 
     */
    public int getMealFat() {
        return mealFat;
    }

    /**
     * Sets the value of the mealFat property.
     * 
     */
    public void setMealFat(int value) {
        this.mealFat = value;
    }

    @Override
    public String toString() {
        return "('"  + userId
                + "','" + mealDate +
                "','" + mealKcal +
                "','" + mealProtein +
                "','" + mealCarbon +
                "','" + mealFat + "')";
    }
}
