//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.16 at 09:26:23 PM MSK 
//


package model.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for schedule complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="schedule">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="schedule_id">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="user_id">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="exercise_id">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="exercise_order">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "schedule", propOrder = {
    "scheduleId",
    "userId",
    "exerciseId",
    "exerciseOrder"
})
public class Schedule {

    public Schedule() {
    }

    public Schedule(int userId, int exerciseId, int exerciseOrder) {
        this.userId = userId;
        this.exerciseId = exerciseId;
        this.exerciseOrder = exerciseOrder;
    }

    public Schedule(int scheduleId, int userId, int exerciseId, int exerciseOrder) {
        this.scheduleId = scheduleId;
        this.userId = userId;
        this.exerciseId = exerciseId;
        this.exerciseOrder = exerciseOrder;
    }

    @XmlElement(name = "schedule_id")
    protected int scheduleId;
    @XmlElement(name = "user_id")
    protected int userId;
    @XmlElement(name = "exercise_id")
    protected int exerciseId;
    @XmlElement(name = "exercise_order")
    protected int exerciseOrder;

    /**
     * Gets the value of the scheduleId property.
     * 
     */
    public int getScheduleId() {
        return scheduleId;
    }

    /**
     * Sets the value of the scheduleId property.
     * 
     */
    public void setScheduleId(int value) {
        this.scheduleId = value;
    }

    /**
     * Gets the value of the userId property.
     * 
     */
    public int getUserId() {
        return userId;
    }

    /**
     * Sets the value of the userId property.
     * 
     */
    public void setUserId(int value) {
        this.userId = value;
    }

    /**
     * Gets the value of the exerciseId property.
     * 
     */
    public int getExerciseId() {
        return exerciseId;
    }

    /**
     * Sets the value of the exerciseId property.
     * 
     */
    public void setExerciseId(int value) {
        this.exerciseId = value;
    }

    /**
     * Gets the value of the exerciseOrder property.
     * 
     */
    public int getExerciseOrder() {
        return exerciseOrder;
    }

    /**
     * Sets the value of the exerciseOrder property.
     * 
     */
    public void setExerciseOrder(int value) {
        this.exerciseOrder = value;
    }

    @Override
    public String toString() {
        return "('"  + userId
                + "','" + exerciseId +
                "','" + exerciseOrder + "')";
    }
}
